### ISSUE TITLE
[댓글 수정 API] 댓글 수정 API 관련 오류

### ISSUE THREAD

**Issue by jsl0149** [chasw0326/club#66]
![image](https://user-images.githubusercontent.com/76390004/169686484-99939d15-339c-4f0c-a77c-c4637bdc6d96.png)
명세서에는 이렇게 작성되어있는데 
`content : 수정내용` 으로 요청을 보낼 시 
![image](https://user-images.githubusercontent.com/76390004/169686644-702b37d4-bc26-4825-88c5-06869ed7a665.png)
이렇게 수정된 내용에 `content` 키 값 까지 같이 출력이 됩니다. 
그래서 수정내용만 key값 없이 문자열 그대로 전송하면
![image](https://user-images.githubusercontent.com/76390004/169686563-9796f957-f425-4863-b9ef-dddac9a345a9.png)
큰 따옴표와 같이 내용이 출력 됩니다. 

확인 부탁드리겠습니다!

**Comment by chasw0326** [comment]
수정했습니다.
